name: ArmamentsEffects
main: org.cubeville.effects.Effects
author: KipperOrigin, GoalieGuy6, FrediW
version: 1.2

depend: [CVTools]
softdepend: [ProtocolLib]

commands:
  fx:
    description: effects management command
    usage: /fx
    permission: fx.admin

permissions:
  ae.main:
    description: All Armaments Effects Permissions.
    default: op
    children:
      ae.drain: true
      ae.explode: true
      ae.potion: true
      ae.instakill: true
      ae.spawn: true
      ae.velocity: true
  ae.drain:
    description: Able to use Drain.
    default: op
  ae.explode:
    description: Able to use Explode.
    default: op
  ae.potion:
    description: Able to use all Potion Effects.
    default: op
  ae.instakill:
    description: Able to use Instakill Effect.
    default: op
  ae.velocity:
    description: Able to use projectile velocity.
    default: op
  ae.spawn:
    description: Able to use mob spawn effect.
    default: op
  ae.admin:
    description: Able to override event cancels.
    default: op
  fx.admin:
    description: Able to use the fx command
    default: op
